// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBstMwFXaAY6r6bp6U7OU8TnQRbo9irPvw',
    appId: '1:366213793866:web:cd8699e5d830a1f5cd7eb3',
    messagingSenderId: '366213793866',
    projectId: 'valencia-6bc29',
    authDomain: 'valencia-6bc29.firebaseapp.com',
    storageBucket: 'valencia-6bc29.firebasestorage.app',
    measurementId: 'G-S2SN1BPB56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC82ZZVNVF-ykqxFb8PpOLrXGj9LSraItQ',
    appId: '1:366213793866:android:26bd67e34bcb5c0bcd7eb3',
    messagingSenderId: '366213793866',
    projectId: 'valencia-6bc29',
    storageBucket: 'valencia-6bc29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp20xSwA_PWVU45lt4PS1-KilSgWxY0u0',
    appId: '1:366213793866:ios:f9ccffc3200e0d64cd7eb3',
    messagingSenderId: '366213793866',
    projectId: 'valencia-6bc29',
    storageBucket: 'valencia-6bc29.firebasestorage.app',
    iosBundleId: 'com.example.valencia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp20xSwA_PWVU45lt4PS1-KilSgWxY0u0',
    appId: '1:366213793866:ios:f9ccffc3200e0d64cd7eb3',
    messagingSenderId: '366213793866',
    projectId: 'valencia-6bc29',
    storageBucket: 'valencia-6bc29.firebasestorage.app',
    iosBundleId: 'com.example.valencia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBstMwFXaAY6r6bp6U7OU8TnQRbo9irPvw',
    appId: '1:366213793866:web:3e6574947dad2954cd7eb3',
    messagingSenderId: '366213793866',
    projectId: 'valencia-6bc29',
    authDomain: 'valencia-6bc29.firebaseapp.com',
    storageBucket: 'valencia-6bc29.firebasestorage.app',
    measurementId: 'G-Z7GNX4HNCD',
  );
}
