extend type Category {
  """
  ✨ List `NoItemCategory` objects in a one-to-many relationship (where `NoItemCategory`.`category` is this object).
  """
  noItemCategories_on_category(
    """
    Filter condition to narrow down the query results.
    """
    where: NoItemCategory_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [NoItemCategory_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: NoItemCategory_Having
  ): [NoItemCategory!]! @fdc_generated(from: "NoItemCategory.category", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `NoItem` objects using `NoItemCategory` as the join table (a `NoItemCategory` object exists where its `category` is this and its `noItem` is that).
  """
  noItems_via_NoItemCategory(
    """
    Filter condition to narrow down the query results.
    """
    where: NoItemCategory_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [NoItemCategory_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: NoItemCategory_Having
  ): [NoItem!]! @fdc_generated(from: "NoItemCategory", purpose: QUERY_MULTIPLE_MANY_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Category", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Category` table.
  """
  _count: Int! @fdc_generated(from: "Category.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Category` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Category.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Category` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Category.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Category` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Category.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Category` table where the `isDefault` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  isDefault_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Category.isDefault", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Category` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Category.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Category` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Category.userId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `Category` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Category.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Category` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Category.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Category.id", purpose: GLOBAL_ID)
}
extend type NoItem {
  """
  ✨ List `NoItemCategory` objects in a one-to-many relationship (where `NoItemCategory`.`noItem` is this object).
  """
  noItemCategories_on_noItem(
    """
    Filter condition to narrow down the query results.
    """
    where: NoItemCategory_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [NoItemCategory_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: NoItemCategory_Having
  ): [NoItemCategory!]! @fdc_generated(from: "NoItemCategory.noItem", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Category` objects using `NoItemCategory` as the join table (a `NoItemCategory` object exists where its `noItem` is this and its `category` is that).
  """
  categories_via_NoItemCategory(
    """
    Filter condition to narrow down the query results.
    """
    where: NoItemCategory_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [NoItemCategory_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: NoItemCategory_Having
  ): [Category!]! @fdc_generated(from: "NoItemCategory", purpose: QUERY_MULTIPLE_MANY_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "NoItem", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `NoItem` table.
  """
  _count: Int! @fdc_generated(from: "NoItem.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `NoItem` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "NoItem.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `NoItem` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "NoItem.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `NoItem` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "NoItem.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `NoItem` table where the `isPublic` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  isPublic_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "NoItem.isPublic", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `NoItem` table where the `lastRevisitedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  lastRevisitedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "NoItem.lastRevisitedAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `NoItem` table where the `reason` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  reason_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "NoItem.reason", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `NoItem` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "NoItem.userId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `NoItem` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "NoItem.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `lastRevisitedAt` field in the `NoItem` table.
  """
  lastRevisitedAt_min: Timestamp @fdc_generated(from: "NoItem.lastRevisitedAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `NoItem` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "NoItem.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `lastRevisitedAt` field in the `NoItem` table.
  """
  lastRevisitedAt_max: Timestamp @fdc_generated(from: "NoItem.lastRevisitedAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "NoItem.id", purpose: GLOBAL_ID)
}
extend type NoItemCategory {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "NoItemCategory", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `NoItemCategory` table.
  """
  _count: Int! @fdc_generated(from: "NoItemCategory.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `NoItemCategory` table where the `categoryId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  categoryId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "NoItemCategory.categoryId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `NoItemCategory` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "NoItemCategory.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `NoItemCategory` table where the `noItemId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  noItemId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "NoItemCategory.noItemId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `NoItemCategory` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "NoItemCategory.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `NoItemCategory` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "NoItemCategory.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "NoItemCategory.noItemId,categoryId", purpose: GLOBAL_ID)
}
extend type User {
  """
  ✨ List `Category` objects in a one-to-many relationship (where `Category`.`user` is this object).
  """
  categories_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: Category_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Category_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Category_Having
  ): [Category!]! @fdc_generated(from: "Category.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `NoItem` objects in a one-to-many relationship (where `NoItem`.`user` is this object).
  """
  noItems_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: NoItem_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [NoItem_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: NoItem_Having
  ): [NoItem!]! @fdc_generated(from: "NoItem.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "User", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `User` table.
  """
  _count: Int! @fdc_generated(from: "User.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `displayName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  displayName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.displayName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `email` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  email_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.email", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `photoUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  photoUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.photoUrl", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `User` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "User.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `User` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "User.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "User.id", purpose: GLOBAL_ID)
}
